CREATE TABLE posts (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(32) NOT NULL,
  content TEXT NOT NULL,
  date DATETIME NOT NULL
);

CREATE TABLE commits (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  user TEXT NOT NULL,
  additions INTEGER NOT NULL,
  deletions INTEGER NOT NULL,
  hash TEXT NOT NULL,
  repo_owner TEXT NOT NULL,
  repo_name TEXT NOT NULL,
  date DATETIME NOT NULL
);
